# -*- coding: utf-8 -*-
"""prj2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhXQ6a7Kb8XeJavLc0xlAGCER-Ft6L6f
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('messy_ecommerce_sales_data.csv')

df.head()

df.describe()

df.info()

data1 = df.loc[:,["Product Name","Profit"]]

data1.isnull().sum()

data1.head()

sns.set(style="whitegrid")

plt.figure(figsize=(12,6))

sample = data1.sort_values(by='Profit', ascending=False).head(10)

sns.lineplot(data=sample, x='Product Name', y='Profit', marker='o')

plt.title('Profit by Product Name')
plt.xlabel('Product Name')
plt.ylabel('Profit')

plt.xticks(rotation=80)

plt.show()