# -*- coding: utf-8 -*-
"""prj3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jr2-zTWo7mnRWeuZotwasL7vQ-rGnFoi
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('dirty_healthy_diet_calorie_intake.csv')

df.head()

df.describe()

df.info()

data1 = df.loc[:,["Person_ID","Health_Status"]]

data1.isnull().sum()

data1.head()

sns.set(style="whitegrid")

plt.figure(figsize=(12,6))

sample = data1.head(10)

sns.histplot(data=sample, x='Person_ID')

plt.title('Distribution of First 10 Person IDs')
plt.xlabel('Person ID')
plt.ylabel('Count')

plt.show()