# -*- coding: utf-8 -*-
"""prj4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gztHvgFHtaqHxgNTWE_ja670j_XvaNWn
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('messy_Student_Social_Media_Mental_Health.csv')

df.head()

df.describe()

df.info()

data1 = df.loc[:,["Age"]]

data1.isnull().sum()

data1.head()

sns.set(style="whitegrid")

plt.figure(figsize=(12,6))

sample = data1.head(10)

sns.histplot(data=sample, x='Age')

plt.title('Distribution of Age')
plt.xlabel('Age')
plt.ylabel('Count')

plt.show()