# -*- coding: utf-8 -*-
"""prj5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OfOtKDH3z8qMm7aY0_ea-01YZmyXzduO
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('student-lifestyle-and-stress-dataset.csv')

df.head()

df.describe()

df.info()

data1 = df.loc[:,["Stress_Level"]]

data1.isnull().sum()

data1.head()

sns.set(style="whitegrid")

plt.figure(figsize=(12,6))

sample = data1.head(10)

sns.boxplot(data=sample, y='Stress_Level')

plt.title('Box Plot of Stress Level')
plt.ylabel('Stress Level')

plt.show()